//go:build ignore

// Package main generates certifier tables from the frozen successor checkpoint.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strconv"
)

const (
	certifiedConstructsInputPath = "../../tests/fixtures/github_ci_successor_checkpoint/tables/certified_constructs.json"
	reasonCodesInputPath         = "../../tests/fixtures/github_ci_successor_checkpoint/tables/reason_codes.json"
	tablesOutputPath             = "tables_gen.go"
)

type constructDocument struct {
	Parser              string `json:"parser"`
	TraversalConvention struct {
		ContainerRule string `json:"container_rule"`
		WildcardRule  string `json:"wildcard_rule"`
	} `json:"traversal_convention"`
	ExportedNodeTypes []string       `json:"exported_node_types"`
	Rows              []constructRow `json:"rows"`
}

type constructRow struct {
	Node        string `json:"node"`
	Role        string `json:"role"`
	Disposition string `json:"disposition"`
	Spec        string `json:"spec"`
	Code        string `json:"-"`
}

type reasonDocument struct {
	Rows []reasonRow `json:"rows"`
}

type reasonRow struct {
	Code               string `json:"code"`
	Scope              string `json:"scope"`
	StableReason       string `json:"stable_reason"`
	ScanReasonCategory string `json:"scan_reason_category"`
	D4Mapping          string `json:"d4_mapping"`
}

func main() {
	if err := generateTables(); err != nil {
		fmt.Fprintf(os.Stderr, "generate tables: %v\n", err)
		os.Exit(1)
	}
}

func generateTables() error {
	constructs, err := readConstructs()
	if err != nil {
		return err
	}
	reasons, err := readReasons()
	if err != nil {
		return err
	}
	if err := assignConstructCodes(constructs.Rows, reasons.Rows); err != nil {
		return err
	}

	sort.Slice(constructs.Rows, func(left, right int) bool {
		if constructs.Rows[left].Node != constructs.Rows[right].Node {
			return constructs.Rows[left].Node < constructs.Rows[right].Node
		}
		return constructs.Rows[left].Role < constructs.Rows[right].Role
	})
	sort.Slice(reasons.Rows, func(left, right int) bool {
		return reasons.Rows[left].Code < reasons.Rows[right].Code
	})

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	output.WriteString("// Package main contains certifier tables generated from the frozen checkpoint.\n")
	output.WriteString("package main\n\n")
	output.WriteString("type constructKey struct {\n\tnode, role string\n}\n\n")
	output.WriteString("type constructRule struct {\n\tdisposition, code string\n}\n\n")
	output.WriteString("const (\n")
	fmt.Fprintf(&output, "\tcertifiedNodeTypeCount int = %d\n", len(constructs.ExportedNodeTypes))
	fmt.Fprintf(&output, "\ttraversalContainerRuleDoc string = %s\n", strconv.Quote(constructs.TraversalConvention.ContainerRule))
	fmt.Fprintf(&output, "\twildcardRuleDoc string = %s\n", strconv.Quote(constructs.TraversalConvention.WildcardRule))
	output.WriteString(")\n\n")
	output.WriteString("var certifiedConstructs = map[constructKey]constructRule{\n")
	for _, row := range constructs.Rows {
		fmt.Fprintf(&output, "\t{node: %s, role: %s}: {disposition: %s, code: %s},\n", strconv.Quote(row.Node), strconv.Quote(row.Role), strconv.Quote(row.Disposition), strconv.Quote(row.Code))
	}
	output.WriteString("}\n\n")
	output.WriteString("var reasonScopes = map[string]string{\n")
	for _, row := range reasons.Rows {
		fmt.Fprintf(&output, "\t%s: %s,\n", strconv.Quote(row.Code), strconv.Quote(row.Scope))
	}
	output.WriteString("}\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return fmt.Errorf("format generated tables: %w", err)
	}
	if err := os.WriteFile(tablesOutputPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", tablesOutputPath, err)
	}
	return nil
}

func assignConstructCodes(constructs []constructRow, reasons []reasonRow) error {
	scopes := make(map[string]string, len(reasons))
	for _, reason := range reasons {
		scopes[reason.Code] = reason.Scope
	}
	for index := range constructs {
		row := &constructs[index]
		if row.Disposition != "refuse" {
			row.Code = ""
			continue
		}
		row.Code = constructRefusalCode(row.Node)
		scope, ok := scopes[row.Code]
		if !ok {
			return fmt.Errorf("construct %q/%q references unknown reason code %q", row.Node, row.Role, row.Code)
		}
		expectedScope, ok := constructRefusalScope(row.Code)
		if !ok {
			return fmt.Errorf("construct %q/%q references reason code %q without an expected scope", row.Node, row.Role, row.Code)
		}
		if scope != expectedScope {
			return fmt.Errorf("construct %q/%q references reason code %q with scope %q, want %q", row.Node, row.Role, row.Code, scope, expectedScope)
		}
	}
	return nil
}

func constructRefusalScope(code string) (string, bool) {
	switch code {
	case "unsupported-construct":
		return "terminal", true
	case "redirect-unsupported", "expansion-unsupported":
		return "subtree-local", true
	default:
		return "", false
	}
}

func constructRefusalCode(node string) string {
	switch node {
	case "RedirOperator":
		return "redirect-unsupported"
	case "ArithmExp", "ArithmExpr", "BinAritOperator", "BinaryArithm", "BraceExp",
		"DblQuoted", "Expansion", "ExtGlob",
		"FlagsArithm", "GlobOperator", "ParamExp", "ParenArithm", "ParExpOperator",
		"ParNamesOperator", "Replace", "Slice", "UnAritOperator", "UnaryArithm",
		"WordPart":
		return "expansion-unsupported"
	default:
		return "unsupported-construct"
	}
}

func readConstructs() (*constructDocument, error) {
	var document constructDocument
	if err := readJSONFile(certifiedConstructsInputPath, &document); err != nil {
		return nil, err
	}
	if len(document.Rows) == 0 {
		return nil, errors.New("certified construct rows must not be empty")
	}
	if len(document.ExportedNodeTypes) == 0 {
		return nil, errors.New("exported node types must not be empty")
	}
	if document.TraversalConvention.ContainerRule == "" || document.TraversalConvention.WildcardRule == "" {
		return nil, errors.New("traversal convention rules must not be empty")
	}

	nodeTypes := make(map[string]struct{}, len(document.ExportedNodeTypes))
	for _, nodeType := range document.ExportedNodeTypes {
		if nodeType == "" {
			return nil, errors.New("exported node type must not be empty")
		}
		if _, exists := nodeTypes[nodeType]; exists {
			return nil, fmt.Errorf("duplicate exported node type %q", nodeType)
		}
		nodeTypes[nodeType] = struct{}{}
	}

	keys := make(map[string]struct{}, len(document.Rows))
	for _, row := range document.Rows {
		if row.Node == "" || row.Role == "" {
			return nil, errors.New("certified construct row is missing node or role")
		}
		if row.Disposition != "traverse" && row.Disposition != "ignore" && row.Disposition != "refuse" {
			return nil, fmt.Errorf("construct %q/%q has invalid disposition %q", row.Node, row.Role, row.Disposition)
		}
		key := row.Node + "\x00" + row.Role
		if _, exists := keys[key]; exists {
			return nil, fmt.Errorf("duplicate certified construct key %q/%q", row.Node, row.Role)
		}
		keys[key] = struct{}{}
	}
	return &document, nil
}

func readReasons() (*reasonDocument, error) {
	var document reasonDocument
	if err := readJSONFile(reasonCodesInputPath, &document); err != nil {
		return nil, err
	}
	if len(document.Rows) == 0 {
		return nil, errors.New("reason code rows must not be empty")
	}

	codes := make(map[string]struct{}, len(document.Rows))
	for _, row := range document.Rows {
		if row.Code == "" || row.Scope == "" {
			return nil, errors.New("reason code row is missing code or scope")
		}
		if row.Scope != "terminal" && row.Scope != "subtree-local" && row.Scope != "command-local" {
			return nil, fmt.Errorf("reason code %q has invalid scope %q", row.Code, row.Scope)
		}
		if _, exists := codes[row.Code]; exists {
			return nil, fmt.Errorf("duplicate reason code %q", row.Code)
		}
		codes[row.Code] = struct{}{}
	}
	return &document, nil
}

func readJSONFile(path string, target any) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if err := rejectDuplicateJSONFields(data); err != nil {
		return fmt.Errorf("decode %s: %w", path, err)
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return fmt.Errorf("decode %s: %w", path, err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return fmt.Errorf("decode %s: trailing JSON data", path)
	}
	return nil
}

func rejectDuplicateJSONFields(data []byte) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	if err := consumeUniqueJSONValue(decoder); err != nil {
		return err
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return errors.New("trailing JSON data")
	}
	return nil
}

func consumeUniqueJSONValue(decoder *json.Decoder) error {
	token, err := decoder.Token()
	if err != nil {
		return err
	}
	delimiter, isDelimiter := token.(json.Delim)
	if !isDelimiter {
		return nil
	}

	switch delimiter {
	case '{':
		fields := make(map[string]struct{})
		for decoder.More() {
			keyToken, err := decoder.Token()
			if err != nil {
				return err
			}
			key, ok := keyToken.(string)
			if !ok {
				return errors.New("JSON object contains a non-string key")
			}
			if _, exists := fields[key]; exists {
				return fmt.Errorf("duplicate JSON field %q", key)
			}
			fields[key] = struct{}{}
			if err := consumeUniqueJSONValue(decoder); err != nil {
				return err
			}
		}
		closing, err := decoder.Token()
		if err != nil {
			return err
		}
		if closing != json.Delim('}') {
			return errors.New("JSON object has an invalid terminator")
		}
	case '[':
		for decoder.More() {
			if err := consumeUniqueJSONValue(decoder); err != nil {
				return err
			}
		}
		closing, err := decoder.Token()
		if err != nil {
			return err
		}
		if closing != json.Delim(']') {
			return errors.New("JSON array has an invalid terminator")
		}
	default:
		return errors.New("JSON value begins with an invalid delimiter")
	}
	return nil
}
