// Code generated by go generate; DO NOT EDIT.

// Package main contains certifier tables generated from the frozen checkpoint.
package main

type constructKey struct {
	node, role string
}

type constructRule struct {
	disposition, code string
}

const (
	certifiedNodeTypeCount    int    = 72
	traversalContainerRuleDoc string = "S3.2: a node with a traverse disposition consumes its child words, word-parts, and role-covered children directly within that role, and it recurses into nested statement-bearing parts (for example, a CmdSubst embedded inside a Word) without re-dispatching those children through this table."
	wildcardRuleDoc           string = "S3.2: a row with role \"*\" applies only when the node is encountered in a role not covered by any explicit (node, role) row in this table, so a wildcard refuse row never overrides in-role consumption performed by a traverse container."
)

var certifiedConstructs = map[constructKey]constructRule{
	{node: "ArithmCmd", role: "*"}:                      {disposition: "refuse", code: "unsupported-construct"},
	{node: "ArithmExp", role: "*"}:                      {disposition: "refuse", code: "expansion-unsupported"},
	{node: "ArithmExpr", role: "*"}:                     {disposition: "refuse", code: "expansion-unsupported"},
	{node: "ArrayElem", role: "*"}:                      {disposition: "refuse", code: "unsupported-construct"},
	{node: "ArrayExpr", role: "*"}:                      {disposition: "refuse", code: "unsupported-construct"},
	{node: "Assign", role: "*"}:                         {disposition: "refuse", code: "unsupported-construct"},
	{node: "Assign", role: "value"}:                     {disposition: "traverse", code: ""},
	{node: "BinAritOperator", role: "*"}:                {disposition: "refuse", code: "expansion-unsupported"},
	{node: "BinCmdOperator", role: "*"}:                 {disposition: "refuse", code: "unsupported-construct"},
	{node: "BinTestOperator", role: "*"}:                {disposition: "refuse", code: "unsupported-construct"},
	{node: "BinaryArithm", role: "*"}:                   {disposition: "refuse", code: "expansion-unsupported"},
	{node: "BinaryCmd", role: "operand-statements"}:     {disposition: "traverse", code: ""},
	{node: "BinaryTest", role: "*"}:                     {disposition: "refuse", code: "unsupported-construct"},
	{node: "Block", role: "body-statements"}:            {disposition: "traverse", code: ""},
	{node: "BraceExp", role: "*"}:                       {disposition: "refuse", code: "expansion-unsupported"},
	{node: "CStyleLoop", role: "*"}:                     {disposition: "refuse", code: "unsupported-construct"},
	{node: "CallExpr", role: "argv"}:                    {disposition: "traverse", code: ""},
	{node: "CaseClause", role: "selector-word"}:         {disposition: "traverse", code: ""},
	{node: "CaseItem", role: "patterns-and-body"}:       {disposition: "traverse", code: ""},
	{node: "CaseOperator", role: "*"}:                   {disposition: "refuse", code: "unsupported-construct"},
	{node: "CmdSubst", role: "body-statements"}:         {disposition: "traverse", code: ""},
	{node: "Command", role: "*"}:                        {disposition: "refuse", code: "unsupported-construct"},
	{node: "Comment", role: "*"}:                        {disposition: "ignore", code: ""},
	{node: "CoprocClause", role: "*"}:                   {disposition: "refuse", code: "unsupported-construct"},
	{node: "DblQuoted", role: "*"}:                      {disposition: "refuse", code: "expansion-unsupported"},
	{node: "DeclClause", role: "*"}:                     {disposition: "refuse", code: "unsupported-construct"},
	{node: "Expansion", role: "*"}:                      {disposition: "refuse", code: "expansion-unsupported"},
	{node: "ExtGlob", role: "*"}:                        {disposition: "refuse", code: "expansion-unsupported"},
	{node: "File", role: "top-level-statements"}:        {disposition: "traverse", code: ""},
	{node: "FlagsArithm", role: "*"}:                    {disposition: "refuse", code: "expansion-unsupported"},
	{node: "ForClause", role: "loop-body-and-selector"}: {disposition: "traverse", code: ""},
	{node: "FuncDecl", role: "body"}:                    {disposition: "traverse", code: ""},
	{node: "GlobOperator", role: "*"}:                   {disposition: "refuse", code: "expansion-unsupported"},
	{node: "IfClause", role: "condition-and-body"}:      {disposition: "traverse", code: ""},
	{node: "LangError", role: "*"}:                      {disposition: "refuse", code: "unsupported-construct"},
	{node: "LangVariant", role: "*"}:                    {disposition: "refuse", code: "unsupported-construct"},
	{node: "LetClause", role: "*"}:                      {disposition: "refuse", code: "unsupported-construct"},
	{node: "Lit", role: "*"}:                            {disposition: "refuse", code: "unsupported-construct"},
	{node: "Loop", role: "*"}:                           {disposition: "refuse", code: "unsupported-construct"},
	{node: "Node", role: "*"}:                           {disposition: "refuse", code: "unsupported-construct"},
	{node: "ParExpOperator", role: "*"}:                 {disposition: "refuse", code: "expansion-unsupported"},
	{node: "ParNamesOperator", role: "*"}:               {disposition: "refuse", code: "expansion-unsupported"},
	{node: "ParamExp", role: "*"}:                       {disposition: "refuse", code: "expansion-unsupported"},
	{node: "ParenArithm", role: "*"}:                    {disposition: "refuse", code: "expansion-unsupported"},
	{node: "ParenTest", role: "*"}:                      {disposition: "refuse", code: "unsupported-construct"},
	{node: "ParseError", role: "*"}:                     {disposition: "refuse", code: "unsupported-construct"},
	{node: "Parser", role: "*"}:                         {disposition: "refuse", code: "unsupported-construct"},
	{node: "ParserOption", role: "*"}:                   {disposition: "refuse", code: "unsupported-construct"},
	{node: "Pos", role: "*"}:                            {disposition: "refuse", code: "unsupported-construct"},
	{node: "Printer", role: "*"}:                        {disposition: "refuse", code: "unsupported-construct"},
	{node: "PrinterOption", role: "*"}:                  {disposition: "refuse", code: "unsupported-construct"},
	{node: "ProcOperator", role: "*"}:                   {disposition: "refuse", code: "unsupported-construct"},
	{node: "ProcSubst", role: "*"}:                      {disposition: "refuse", code: "unsupported-construct"},
	{node: "QuoteError", role: "*"}:                     {disposition: "refuse", code: "unsupported-construct"},
	{node: "RedirOperator", role: "*"}:                  {disposition: "refuse", code: "redirect-unsupported"},
	{node: "Redirect", role: "quoted-heredoc-body"}:     {disposition: "ignore", code: ""},
	{node: "Redirect", role: "target-word-expansion"}:   {disposition: "traverse", code: ""},
	{node: "Redirect", role: "unquoted-heredoc-body"}:   {disposition: "traverse", code: ""},
	{node: "Replace", role: "*"}:                        {disposition: "refuse", code: "expansion-unsupported"},
	{node: "SglQuoted", role: "data"}:                   {disposition: "ignore", code: ""},
	{node: "Slice", role: "*"}:                          {disposition: "refuse", code: "expansion-unsupported"},
	{node: "Stmt", role: "command-and-redirects"}:       {disposition: "traverse", code: ""},
	{node: "Subshell", role: "body-statements"}:         {disposition: "traverse", code: ""},
	{node: "TestClause", role: "*"}:                     {disposition: "refuse", code: "unsupported-construct"},
	{node: "TestDecl", role: "*"}:                       {disposition: "refuse", code: "unsupported-construct"},
	{node: "TestExpr", role: "*"}:                       {disposition: "refuse", code: "unsupported-construct"},
	{node: "TimeClause", role: "*"}:                     {disposition: "refuse", code: "unsupported-construct"},
	{node: "UnAritOperator", role: "*"}:                 {disposition: "refuse", code: "expansion-unsupported"},
	{node: "UnTestOperator", role: "*"}:                 {disposition: "refuse", code: "unsupported-construct"},
	{node: "UnaryArithm", role: "*"}:                    {disposition: "refuse", code: "expansion-unsupported"},
	{node: "UnaryTest", role: "*"}:                      {disposition: "refuse", code: "unsupported-construct"},
	{node: "WhileClause", role: "condition-and-body"}:   {disposition: "traverse", code: ""},
	{node: "Word", role: "*"}:                           {disposition: "refuse", code: "unsupported-construct"},
	{node: "WordIter", role: "loop-items"}:              {disposition: "traverse", code: ""},
	{node: "WordPart", role: "*"}:                       {disposition: "refuse", code: "expansion-unsupported"},
}

var reasonScopes = map[string]string{
	"assignment-prefix":                  "command-local",
	"control-flow-keyword":               "command-local",
	"depth-cap":                          "terminal",
	"dispatcher-payload":                 "command-local",
	"dispatcher-selector-unresolved":     "command-local",
	"event-cap":                          "terminal",
	"expansion-unsupported":              "subtree-local",
	"marker-head-look-alike":             "command-local",
	"parser-divergence-guard":            "terminal",
	"policy-unresolvable":                "command-local",
	"redirect-unsupported":               "subtree-local",
	"source-cap":                         "terminal",
	"splitting-unsafe-word":              "command-local",
	"statement-cap":                      "terminal",
	"syntax-error":                       "terminal",
	"unquoted-expansion-in-command-word": "command-local",
	"unstable-first-word":                "command-local",
	"unsupported-construct":              "terminal",
	"work-cap":                           "terminal",
}
